import Image from "next/image";
import type { Metadata } from "next";
import TrustBadges from "@/components/TrustBadges";
import Newsletter from "@/components/Newsletter";

export const metadata: Metadata = { title: "Sobre nosotros — GOLTRA", description: "Conoce la historia, los valores y el proceso de calidad detrás de GOLTRA." };
const stats = [{ value: "+50.000", label: "Camisetas enviadas" }, { value: "120+", label: "Clubes y selecciones" }, { value: "4.8/5", label: "Valoración media" }, { value: "30 países", label: "Envíos internacionales" }];
const values = [{ title: "Calidad obsesiva", text: "Cada lote pasa un control de costuras, tejido y bordado antes de salir del taller." }, { title: "Pasión por el fútbol", text: "Somos aficionados antes que vendedores. Elegimos cada equipación pensando en la afición." }, { title: "Envíos rápidos", text: "Trabajamos con logística exprés para que tu camiseta llegue lista para el próximo partido." }];

export default function NosotrosPage() {
  return <main className="bg-paper"><section className="relative overflow-hidden bg-ink text-white"><div className="mx-auto max-w-5xl px-5 py-24 text-center sm:px-8"><span className="text-xs font-bold uppercase tracking-[0.2em] text-volt">Nuestra historia</span><h1 className="mt-3 font-display text-5xl tracking-wide sm:text-6xl">Nacimos en las gradas, crecimos con la afición</h1><p className="mx-auto mt-5 max-w-2xl text-base text-paper/70">GOLTRA empezó como un proyecto entre amigos aficionados al fútbol que no encontraban réplicas con la calidad que buscaban. Hoy somos una comunidad que viste sus colores con orgullo.</p></div></section><section className="mx-auto max-w-7xl px-5 py-16 sm:px-8" id="calidad"><div className="grid items-center gap-10 md:grid-cols-2"><div className="relative aspect-[4/3] overflow-hidden rounded-3xl"><Image src="/images/about-workshop.jpg" alt="Taller de confección" fill className="object-cover" /></div><div><span className="text-xs font-bold uppercase tracking-[0.2em] text-flame">Calidad y materiales</span><h2 className="mt-2 font-display text-4xl tracking-wide text-ink">Del hilo al escudo, cuidamos cada detalle</h2><p className="mt-4 text-sm leading-relaxed text-ink/65">Seleccionamos tejidos técnicos transpirables y trabajamos con talleres especializados en bordado de precisión. Antes de cada envío, un equipo de control de calidad revisa costuras, serigrafías y tallaje para garantizar la mejor experiencia posible.</p></div></div><div className="mt-16 grid grid-cols-2 gap-6 rounded-3xl bg-ink p-10 text-center text-white md:grid-cols-4">{stats.map((s) => <div key={s.label}><p className="font-display text-4xl tracking-wide text-volt">{s.value}</p><p className="mt-1 text-xs uppercase tracking-wide text-paper/60">{s.label}</p></div>)}</div><div className="mt-16 grid gap-6 md:grid-cols-3">{values.map((v) => <div key={v.title} className="rounded-2xl border border-ink/10 bg-white p-7"><h3 className="font-display text-2xl tracking-wide text-ink">{v.title}</h3><p className="mt-2 text-sm leading-relaxed text-ink/65">{v.text}</p></div>)}</div></section><TrustBadges /><Newsletter /></main>;
}
